// Generated by CoffeeScript 1.5.0
(function() {
  var checkImages, getImages, init, location, pageSize;

  pageSize = 25;

  jQuery(function() {
    var $;
    $ = jQuery;
    return init();
  });

  init = function() {
    if (Modernizr.geolocation) {
      return navigator.geolocation.getCurrentPosition(location);
    } else {
      return console.log("no geo :-(");
    }
  };

  location = function(position) {
    var lat, lon, url;
    lat = parseFloat(position.coords.latitude);
    lon = parseFloat(position.coords.longitude);
    url = ("http://api.geonames.org/findNearbyWikipediaJSON?lat=" + lat + "&lng=" + lon + "&radius=10&username=wikimedia&maxRows=") + pageSize;
    return $.ajax({
      url: url,
      dataType: "jsonp",
      jsonpCallback: 'articles'
    });
  };

  this.articles = function(geo) {
    var article, ul, _i, _len, _ref;
    ul = $("#results");
    _ref = geo.geonames;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      article = _ref[_i];
      ul.append($("<li><a class='title' href='http://" + article.wikipediaUrl + "'>" + article.title + "</a><span class='summary hidden-phone'>: " + article.summary + "</span></li>"));
    }
    return checkImages();
  };

  checkImages = function() {
    return $("#results li").each(function(i, li) {
      var title;
      title = $(this).find("a").text();
      return getImages(title, function(images) {
        if (images.length === 0) {
          console.log("" + title + " needs image");
          return $(li).addClass("needImage");
        }
      });
    });
  };

  getImages = function(title, callback) {
    var url;
    url = "http://en.wikipedia.org/w/api.php?action=query&prop=images&format=json&titles=" + title + "&callback=?&imlimit=500";
    return $.getJSON(url, function(data) {
      var images, page, pageId, _ref;
      images = [];
      _ref = data.query.pages;
      for (pageId in _ref) {
        page = _ref[pageId];
        if (page.images != null) {
          images = page.images;
        }
        break;
      }
      return callback(images);
    });
  };

}).call(this);
